################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
SRC_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
SECONDARY_SIZE := 
COMPILED_SRCS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Source/0_Rte \
Source/1_Common \
Source/2_App/BswCom \
Source/2_App/BswDcm \
Source/3_EcuAbs/Adc \
Source/3_EcuAbs/Can \
Source/3_EcuAbs/Dio \
Source/3_EcuAbs/Gpt \
Source/3_EcuAbs/Mcu \
Source/3_EcuAbs/Nvm \
Source/3_EcuAbs \
Source/3_EcuAbs/Spi \
Source/3_EcuAbs/Wdg \
Source/4_Cdd/CcpCustom \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/adc \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/can \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/dio \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/ecum \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/fee_infineon_tricore/src \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/fls_17_pmu_infineon_tricore/src \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/flsloader_infineon_tricore/src \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/gpt \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/icu \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/irq \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/mcu \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/port \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/pwm \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/spi \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/tricore_general \
Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/wdg \
Source/5_Bsw/Mcal/McalTraining/cfg/src \
Source/5_Bsw/Service/Os \
Source/5_Bsw/Service/SchM \
Source \
Training_00/Source/0_Rte \
Training_00/Source/1_Common \
Training_00/Source/2_App/BswCom \
Training_00/Source/2_App/BswDcm \
Training_00/Source/3_EcuAbs/Adc \
Training_00/Source/3_EcuAbs/Can \
Training_00/Source/3_EcuAbs/Dio \
Training_00/Source/3_EcuAbs/Gpt \
Training_00/Source/3_EcuAbs/Mcu \
Training_00/Source/3_EcuAbs/Nvm \
Training_00/Source/3_EcuAbs \
Training_00/Source/3_EcuAbs/Spi \
Training_00/Source/3_EcuAbs/Wdg \
Training_00/Source/4_Cdd/CcpCustom \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/adc \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/can \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/dio \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/ecum \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/fee_infineon_tricore/src \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/fls_17_pmu_infineon_tricore/src \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/flsloader_infineon_tricore/src \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/gpt \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/icu \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/irq \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/mcu \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/port \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/pwm \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/spi \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/tricore_general \
Training_00/Source/5_Bsw/Mcal/AURIX_MC-ISAR_AS4XX_AURIX_TC23X_AC_V201/wdg \
Training_00/Source/5_Bsw/Mcal/McalTraining/cfg/src \
Training_00/Source/5_Bsw/Service/Os \
Training_00/Source/5_Bsw/Service/SchM \
Training_00/Source \
Training_00 \
. \

